### ISSUE TITLE
Error using 2021R1 build 21.103.0054 - "The type initializer for 'ListPMTaskAttribute' threw an exception."

### ISSUE THREAD

**Issue by GrahamTheHat** [Acumatica/Acumatica-Smartsheet#8]
The new install from this site imported and published fine. However on attempting to access the Project Preferences screen the following error occurs:-

"**We're sorry! An error has occurred while processing your request. A report has been generated for our technical staff to investigate the problem. Please try to repeat your request later. Thank you for understanding.**"

Reviewing the trace shows this:-

**Error: | The type initializer for 'ListPMTaskAttribute' threw an exception.**

Raised At: 	06/05/2021 13:03:35 | Screen: 	PM.10.10.00 |

Details: 

Error: The type initializer for 'ListPMTaskAttribute' threw an exception.  

System.NullReferenceException: Object reference not set to an instance of an object.
    at PX.Data.PXSelectorAttribute.populateFields(PXCache sender, Boolean bypassInit)
    at PX.Data.PXSelectorAttribute.CacheAttached(PXCache sender)
    at PX.Data.PXEventSubscriberAttribute.InvokeCacheAttached(PXCache cache)
    at PX.Data.PXCache'1..ctor(PXGraph graph)
    at PX.Data.PXCacheCollection.get_Item(Type key)
    at PX.Data.PXAction'1.AppendAttributes(String name, Object[] attributes)
    at PX.Data.PXAction'1.SetHandler(Delegate handler, String name)
    at PX.Data.PXAction'1..ctor(PXGraph graph, String name)
    at _Initialize(PXGraph )    at PX.Data.PXGraph._InitializeDelegate.Invoke(PXGraph graph)
    at PX.Data.PXGraph..ctor()
    at PX.Data.PXGraph'2..ctor()
    at PX.Objects.PM.ProjectEntry..ctor()
    at PX.Data.PXGraph.CreateInstance(Type graphType, String prefix)
    at PX.Data.PXGraph.CreateInstance(Type graphType)
    at PX.Data.PXGraph.CreateInstance[Graph]()
    at SmartSheetIntegration.PMSSMapping.nameAcu.ListPMTaskAttribute..cctor()
    at System.RuntimeTypeHandle.CreateCaInstance(RuntimeType type, IRuntimeMethodInfo ctor)
    at  System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule  decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount,  RuntimeType attributeFilterType, Boolean mustBeInheritable, IList  derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimePropertyInfo property, RuntimeType caType)
    at PX.Data.PXExtensionManager.GetCustomAttributesEx(MemberInfo t, Type filter, Boolean inherit)
    at PX.Data.PXCache'1.getEventSubcriberAttributes(Type typenode,  Dictionary`2 extproperties, DACFieldDescriptor prop, Dictionary'2  cstInjectedProps, Dictionary'2 baseinfos)
    at PX.Data.PXCache'1.buildCacheStaticInfo(Type typenode, Boolean ignoredResult, ListOfTypes lot)
    at PX.Data.PXCache'1._Initialize(Boolean ignoredResult)
    at PX.Data.PXCache'1..ctor(PXGraph graph)
    at PX.Data.PXCacheCollection.get_Item(Type key)
    at PX.Data.PXView.CacheLazyLoad()
    at PX.Data.PXView.get__Cache()
    at PX.Data.PXView.get_Cache()
    at SmartSheetIntegration.SetupMaintExt.Initialize()
    at PX.Data.PXGraph.CreateInstance(Type graphType, String prefix)
    at PX.Web.UI.PXBaseDataSource.CreateDataGraphAsSingleton(Type type)
    at PX.Web.UI.PXBaseDataSource.CreateDataGraph(Type type)
    at PX.Web.UI.PXBaseDataSource.get_DataGraph()
    at User_PageTitle.InitAuditMenu()
    at User_PageTitle.Page_InitComplete(Object sender, EventArgs e)
    at System.EventHandler.Invoke(Object sender, EventArgs e)
    at System.Web.UI.Page.OnInitComplete(EventArgs e)
    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

This is also beyond my capability to fix, so if someone could help I would appreciate it very much.

My direct email is graham.martin@kiss-uk.com if you want to reach out to me direct for further info

Many thanks,
Graham

**Comment by GrahamTheHat** [comment]
UPDATE:

I found the issue with 2020R2 as well, so it looks like something in my configuration but I have no idea what. Everything else seems fine - I get the SMARTSheet integrations on Employee forms, I get the Synchronise screen - I just can't get into Project Preferences ... as the error leads with "ListPMTaskAttribute" I even, as a long shot, made sure I didn't have any Project Attributes setup - same issue as before.

Any pointers or clues would be most welcomed ...

Many thanks,

**Comment by jbeiler** [comment]
Has anyone been able to diagnose and fix this error?  I published the recently released update for 2021R1, I'm not getting this error on that site.  But I am getting this error on a site running 2020R2.

**Comment by GrahamTheHat** [comment]
Hi @jbeiler - I've not heard anything else, and I haven't been able to resolve it (but am still continuing to experiment where I can).

My current thought remains that its linked to the Project Management tasks, and my next experiment is to see if its something linked to the state of existing projects at the time of installation. 

I also find I get the same error on trying to access the projects list screen (PM3010PL) I get when trying to access Project Preferences. In all cases I've tried so far I don't have any projects active at the point of installation, so there are no tasks active either and I wonder if the initializer function is not allowing for a result of no valid tasks to work with (hence the "exception"). 

This is where my lack of knowledge in coding lets me down I'm afraid meaning I can't debug this sensibly any further than "guesses". I'm about to try in a new test installation with dummy projects and tasks setup. 

I received an early response from @famadoz who suggested it may be something to do with the options set on the enable/disable screen. I set the options to the same as in the demo environment @dougjohnson7 reported using successfully, but no joy for me.

**Comment by GrahamTheHat** [comment]
Solved !!!

The clue is in the "object reference not found" @jbeiler 

The problem occurs if you PUBLISH without a Project (and therefore Project Tasks) for ListPMTaskAttribute to operate with ...

@dougjohnson7 & @famadoz  - thank you for your help and input to this guys :)
